#!/usr/bin/env python3
import os
import re
import sys
from pathlib import Path

def remove_docstrings(content):
    lines = content.split('\n')
    result = []
    in_docstring = False
    docstring_char = None
    skip_line = False
    
    for i, line in enumerate(lines):
        stripped = line.strip()
        
        if not in_docstring:
            if stripped.startswith('"""') or stripped.startswith("'''"):
                docstring_char = stripped[:3]
                
                if stripped.endswith(docstring_char) and len(stripped) > 6:
                    skip_line = True
                    continue
                else:
                    in_docstring = True
                    continue
            else:
                result.append(line)
        else:
            if docstring_char in line:
                in_docstring = False
                continue
    
    return '\n'.join(result)

def remove_ai_comments(content):
    lines = content.split('\n')
    result = []
    
    ai_patterns = [
        r'#\s*(AI generated|Generated by|Auto-generated|TODO:|FIXME:|NOTE:)',
        r'#\s*\.\.\.',
    ]
    
    for line in lines:
        stripped = line.strip()
        
        is_ai_comment = False
        for pattern in ai_patterns:
            if re.search(pattern, line, re.IGNORECASE):
                is_ai_comment = True
                break
        
        if not is_ai_comment:
            result.append(line)
    
    return '\n'.join(result)

def clean_file(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_lines = len(content.split('\n'))
        
        content = remove_docstrings(content)
        content = remove_ai_comments(content)
        
        content = re.sub(r'\n{3,}', '\n\n', content)
        
        cleaned_lines = len(content.split('\n'))
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        removed = original_lines - cleaned_lines
        if removed > 0:
            print(f"✓ {filepath}: Removed {removed} lines")
            return True
        return False
    
    except Exception as e:
        print(f"✗ {filepath}: Error - {e}")
        return False

def main():
    base_dir = Path(__file__).parent.parent
    
    py_files = []
    for root, dirs, files in os.walk(base_dir):
        dirs[:] = [d for d in dirs if d not in ['.venv', 'venv', 'node_modules', '__pycache__', '.git', '.agent']]
        
        for file in files:
            if file.endswith('.py'):
                filepath = os.path.join(root, file)
                py_files.append(filepath)
    
    print(f"Found {len(py_files)} Python files\n")
    
    cleaned_count = 0
    for filepath in py_files:
        if clean_file(filepath):
            cleaned_count += 1
    
    print(f"\n✓ Cleaned {cleaned_count}/{len(py_files)} files")

if __name__ == "__main__":
    main()
